### ISSUE TITLE
Regal (Rego Linter) Line Length

### ISSUE THREAD

**Issue by Sloane4** [cisagov/ScubaGear#1179]
# 💡 Summary #

What should be the max line length?

## Motivation and context ##

The line length has been in flux because there isn't a strong opinion on what the max should be. Currently it was increased from 120 to 150. Should the line length be reverted to 120 or something else?

## Implementation notes ##

- update regal config for max line length

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Max line length decided on
- [ ] Fix all line length linter violations

**Comment by anderseknert** [comment]
Looks like all of the current violations are in tests, so one option could be to just disable the rule in those files, while still enforce it in regular policies. I..e something like:

```yaml
    line-length:
      # Most of these seem fixable by concatenating strings
      # and by using the non-breakable-word-threshold option
      # for when that doesn't work.
      max-line-length: 150
      non-breakable-word-threshold: 100
      level: error
      ignore:
        files:
          - '*_test.rego'
```
