### ISSUE TITLE
Remove an unnecessary Cmdlet from AAD policy check 5.3 to improve performance of the provider

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#729]
# 💡 Summary #

For Rego policy check 5.3 we can **replace Get-MgBetaPolicyAdminConsentRequestPolicy and use Get-MgBetaDirectorySetting instead**. We already use Get-MgBetaDirectorySetting for policy 5.4 so we can remove the extra cmdlet Get-MgBetaPolicyAdminConsentRequestPolicy from the provider to make AAD run faster.
When developing the functional test cases for AAD I discovered that the Get-MgBetaDirectorySetting returns a field named EnableAdminConsentRequests that we can check to see if the admin consent workflow is enabled. 

In addition to updating the Rego policy check, updating the functional test case yaml code is part of the scope of this issue.
Below I have included a draft functional test case that references the Get-MgBetaDirectorySetting / Update-MgBetaDirectorySetting cmdlets and the EnableAdminConsentRequests field.

```
 - PolicyId: MS.AAD.5.3v1
   TestDriver: RunScuba
   Tests:
     - TestDescription: MS.AAD.5.3v1 Compliant - Users can request admin consent to apps they are unable to consent to
       Preconditions: 
         - Command: UpdateDirectorySettingByName
           Splat:
             DisplayName: Consent Policy Settings
             Updates:
               BodyParameter:
                 Values:
                   - Name: EnableAdminConsentRequests
                     Value: true
       Postconditions: []
       ExpectedResult: true
```

## Acceptance criteria ##

- [x] Provider code has been updated to remove the unnecessary Cmdlet
- [x] Rego policy code has been updated
- [x] Rego unit tests have been updated
- [x] Functional test case has been updated
- [x] All code and functional test have been functionally tested against the test tenants
